### ISSUE TITLE
Unable to use image from Azure Portal

### ISSUE THREAD

**Issue by BecherX64** [wader/postfix-relay#73] opened 2023-02-22 16:17 UTC
We tried start Azure Container Instance using this image but it is not working using Azure Portal or Azure DevOps.
We are getting following error when trying to pull image during deployment:
#[error]InaccessibleImage: The image 'mwader/postfix-relay' in container group 'ci-postfixsmtp01' is not accessible. Please check the image and registry credential.

PS: Normal "docker pull mwader/postfix-relay" on docker enabled VM is working fine.
PS: After we pull/push image into Azure Container Registry we are able to start ACI from such image.

Any idea how we can start ACI directly from public docker image ?

**Comment by wader** [comment] 2023-02-22 17:35
Hi, sorry i have no experience with azure. Could it be that some un-needed credentials are sent with the request etc? did some google for duckerhub public image and the error message, could it be something like https://github.com/MicrosoftDocs/azure-docs/issues/92698?

**Comment by BecherX64** [comment] 2023-02-24 11:45
Hello,
I`ve tried advice from recommended post using "mwader/postfix-relay:latest". Same error. I`ve tried even authenticate using my Docker Hub Account and still no success from Azure Portal :(
I am able to use your other images just this one is NOT working :(

**Comment by wader** [comment] 2023-02-24 12:17
Strange, i can't see anything in my dockerhub dashboard about the image that indicates it's special. What other images did you try? could you try fetch a bogus image name or tag, does it give same error? you could you try `mwader/ydls`?

**Comment by wader** [comment] 2023-05-11 20:00
Did you figure out what was going on here? close?

**Comment by wader** [comment] 2023-05-15 09:40
Closing, but feel free to add comments if you found the root cause

**Closed by wader** 2023-05-15 09:40 UTC
